mode: chatops
silent: true
branchName: '${issue.number}-${issue.title,}'
gitSafeReplacementChar: '-'
autoLinkIssue: true
autoCloseIssue: true
openPR: true
branches:
  - label:
      - bug🐞
    prefix: bug/
  - label:
      - feature-request👓
    prefix: feature/
  - label:
      - new-app💁‍
    prefix: new-app/
  - label:
      - documentation📄
    prefix: documentation/
experimental:
  branchNameArgument: true
